### ISSUE TITLE
How to build the demo project?

### ISSUE THREAD

**Issue by smannaoh** [ethanhann/eeh-navigation#22]
I have downloaded the eeh-navigation demo project from https://github.com/ethanhann/eeh-navigation-demo (linked from https://github.com/ethanhann/eeh-navigation/issues/19).

Can you please outline the steps how to build and run the demo? I have run 'npm install' in the eeh-navigation-demo-master. I am not sure what to do after that. Please help.
Thanks.

**Comment by ethanhann** [comment]
1. npm install
2. bower install
3. gulp serve
4. Visit http://localhost:3000 in your browser.

**Comment by smannaoh** [comment]
Thanks! It worked. 
However, some glyphes were not working in the sidebar. (see attached).
I am also getting the following error in browser (Chrome) console. Not sure if they are related.

TypeError: Cannot read property 'configure' of undefined
    at Object.$get (http://localhost:3000/bower_components/angular-highlightjs/build/angular-highlightjs.js:47:12)
    at Object.invoke (http://localhost:3000/bower_components/angular/angular.js:4478:17)
    at http://localhost:3000/bower_components/angular/angular.js:4295:37
    at getService (http://localhost:3000/bower_components/angular/angular.js:4437:39)
    at Object.invoke (http://localhost:3000/bower_components/angular/angular.js:4469:13)
    at extend.instance (http://localhost:3000/bower_components/angular/angular.js:9136:34)
    at nodeLinkFn (http://localhost:3000/bower_components/angular/angular.js:8248:36)
    at compositeLinkFn (http://localhost:3000/bower_components/angular/angular.js:7680:13)
    at publicLinkFn (http://localhost:3000/bower_components/angular/angular.js:7555:30)
    at http://localhost:3000/bower_components/angular-ui-router/release/angular-ui-router.js:4026:9 <ui-view class="ng-scope">(anonymous function) @ angular.js:12477
![eehnavigation](https://cloud.githubusercontent.com/assets/13316762/10265274/2d54658e-69f8-11e5-8e4b-40fdca99159a.PNG)

**Comment by ethanhann** [comment]
I'm not sure why the icons aren't showing up for you. I wasn't able to reproduce that issue. I fixed the code snippet issue though. It was caused by angular-highlightjs dropping highlightjs as a dependency in its bower.json file (https://github.com/pc035860/angular-highlightjs/issues/28). It's all good now.

**Comment by pdarscht** [comment]
When running gulpe serve (after npm and bower install) comes this error:

```
module.js:338
    throw err;
    ^
Error: Cannot find module 'socket.io-client'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\learn\menu\node_modules\karma\node_modules\socket.io\lib\socket.io.js:12:14)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```

My current versions:

npm -v : 2.5.1
node -v: 0.12.0
gulp 3.9

**Comment by ethanhann** [comment]
@pdarscht Try deleting the node_modules directory and reinstalling.
